services:
  - type: web
    name: adcritic
    runtime: python
    pythonVersion: "3.11.9"
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: adcritic-db
          property: connectionString
      - key: SITE_URL
        value: https://adcritic.world
      - key: ADMIN_EMAIL
        value: admin@adcritic.com
      - key: ADMIN_RESET_PASSWORD
        sync: false
      - key: MEMBERSHIP_HERO_IMAGE_URL
        value: https://res.cloudinary.com/dslebikvo/image/upload/v1783213234/adcritic/images/ibfubiameveuxywqkcxa.jpg
      - key: FOUNDER_SHIELD_IMAGE_URL
        value: https://res.cloudinary.com/dslebikvo/image/upload/v1783215415/adcritic/images/wmh7gbugyszgpzx9mfub.png
      - key: CLOUDINARY_URL
        sync: false
      - key: CLOUDINARY_FOLDER
        value: adcritic
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USE_TLS
        value: "true"
      - key: MAIL_USERNAME
        value: hello@adcritic.world
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_FROM
        value: AdCritic <hello@adcritic.world>

databases:
  - name: adcritic-db
    plan: free
